"""
MediaMTX config generator.

Produces a minimal mediamtx.yml from the camera repository and writes it
into the repository-level infrastructure/ directory so the local MediaMTX
binary can consume it.
"""

import logging
from pathlib import Path

from app.infrastructure.database.camera_repository import camera_repo

logger = logging.getLogger(__name__)


# Repository layout: c2_center/backend/app/infrastructure/mediamtx/client.py
# Walking up 5 parents lands us at c2_center/, then /infrastructure/mediamtx.yml.
INFRA_PATH = Path(__file__).resolve().parents[4] / "infrastructure" / "mediamtx.yml"


def _path_from_rtsp(rtsp_url: str, fallback: str) -> str:
    """Return the last path component of an RTSP URL or fallback to stream id.

    Examples:
      rtsp://localhost:8554/cam1 -> cam1
    """
    if not rtsp_url or "/" not in rtsp_url:
        return fallback
    try:
        return rtsp_url.rsplit("/", 1)[-1]
    except Exception:
        return fallback


def build_config(cameras: list[dict], rtsp_address: str = ":8554", log_level: str = "info") -> str:
    """Render a minimal mediamtx.yml as text from a camera list.

    Only enabled cameras are included by convention because disabled cameras
    should stop at the backend reader layer and not keep reconnecting.
    """
    header = (
        f"# Auto-generated by backend\n"
        f"# Do not edit manually if you rely on the backend deploy endpoint.\n"
        f"logLevel: {log_level}\n\n"
        f"rtspAddress: {rtsp_address}\n"
        f'rtspEncryption: "no"\n'
        f'rtspServerKey: ""\n'
        f'rtspServerCert: ""\n\n'
        f"paths:\n"
    )

    body_lines: list[str] = []
    for cam in cameras:
        if not cam.get("enabled", True):
            continue
        path = _path_from_rtsp(cam.get("rtsp_url", ""), cam.get("stream_id"))
        body_lines.append(f"  {path}:")
        body_lines.append(f"    source: publisher")
        body_lines.append(f"    sourceOnDemand: no")
        body_lines.append("")

    if not body_lines:
        body_lines = ["  # No enabled cameras available"]

    return header + "\n".join(body_lines) + "\n"


def deploy_config(write: bool = True, enabled_only: bool = True) -> dict:
    """Generate and optionally write the mediamtx.yml file.

    Returns a small status dict describing the action.
    """
    cameras = camera_repo.list_cameras(enabled_only=enabled_only)
    content = build_config(cameras)

    if write:
        INFRA_PATH.parent.mkdir(parents=True, exist_ok=True)
        INFRA_PATH.write_text(content, encoding="utf-8")
        logger.info("Wrote mediamtx config: %s", INFRA_PATH)
        return {"path": str(INFRA_PATH), "written": True, "count": len(cameras)}

    return {"path": str(INFRA_PATH), "written": False, "count": len(cameras), "preview": content}
