from __future__ import annotations

# Camera
CAMERA_ID = "Intersection_01"
CAMERA_INDEX = 0
VIDEO_PATH = "/home/jetson/Documents/VID_20260404_181346.mp4"
USE_VIDEO_SOURCE = True

# MQTT
MQTT_BROKER = "192.168.55.100"
MQTT_PORT = 1883
MQTT_TOPIC = "traffic/detections"
LIVE_MQTT_TOPIC = "traffic/live_tracking"
LIVE_VIDEO_TOPIC = "traffic/live_video"
MQTT_QOS = 1
MQTT_PUBLISH_WAIT_TIMEOUT_SECONDS = 2.0

# MinIO
MINIO_URL = "192.168.55.100:9000"
MINIO_ACCESS_KEY = "minioadmin"
MINIO_SECRET_KEY = "minioadminpassword"
MINIO_BUCKET = "raw-data"

# YOLO / Inference
MODEL_PATH = "/home/jetson/Documents/models/best_v8n_pruned.engine"
CONFIDENCE_THRESHOLD = 0.5
ACTIVE_LEARNING_ENABLED = True
ACTIVE_LEARNING_CONF_MIN = 0.35
ACTIVE_LEARNING_CONF_MAX = 0.65
ACTIVE_LEARNING_MIN_BRIGHTNESS = 40.0
ACTIVE_LEARNING_MAX_BRIGHTNESS = 220.0
ACTIVE_LEARNING_MIN_BLUR = 50.0
PUBLISH_COOLDOWN_SECONDS = 6.0
PUBLISH_WINDOW_SECONDS = 10.0
MAX_UPLOADS_PER_WINDOW = 3
FRAME_DEDUP_PHASH_DISTANCE_MAX = 3
RULE_OOD_ENABLED = True
RULE_OOD_VEHICLE_TOP_ZONE_MAX_Y = 0.20
RULE_OOD_EXTREME_AREA_MAX_RATIO = 0.90
RULE_OOD_BUS_VERTICAL_RATIO_MIN = 1.80
RULE_OOD_EDGE_TOUCH_MIN_EDGES = 2
RULE_OOD_EDGE_TOUCH_MIN_AREA_RATIO = 0.60
RULE_OOD_FORBIDDEN_CLASSES = ("toothbrush", "microwave", "oven", "refrigerator", "bed", "toilet")
RULE_OOD_CLASS_ASPECT_RATIO_LIMITS = (
    ("bus", 0.20, 1.80),
    ("truck", 0.25, 2.20),
    ("car", 0.30, 2.50),
    ("motorcycle", 0.35, 3.00),
    ("bicycle", 0.35, 3.20),
    ("person", 0.80, 4.50),
)
RULE_OOD_PERSISTENCE_WINDOW_FRAMES = 5
RULE_OOD_PERSISTENCE_MIN_HITS = 3
RULE_OOD_SCORE_THRESHOLD = 1.0
RULE_OOD_SCORE_FORBIDDEN_CLASS = 2.0
RULE_OOD_SCORE_EXTREME_AREA = 1.4
RULE_OOD_SCORE_BUS_VERTICAL = 1.2
RULE_OOD_SCORE_ASPECT_RATIO = 0.5
RULE_OOD_SCORE_TOP_ZONE_VEHICLE = 0.4
RULE_OOD_SCORE_EDGE_TOUCH = 0.6

# Local buffer
LOCAL_BUFFER_DIR = "./buffer"
LOCAL_DISK_SAFETY_LIMIT_MB = 500

# Threading
RAM_QUEUE_MAXSIZE = 10
LIVE_TELEMETRY_ENABLED = True

# MinIO timeouts
MINIO_CONNECT_TIMEOUT_SECONDS = 0.3
MINIO_READ_TIMEOUT_SECONDS = 0.5

# Sync behavior
MAX_SYNC_FILES_PER_CYCLE = 2
MAX_BUFFER_MESSAGES_PER_CYCLE = 5
BUFFER_MESSAGE_PUBLISH_INTERVAL_SECONDS = 0.1

