"""Minimal MediaMTX config generator and deployer.

Generates a simple mediamtx.yml with paths derived from cameras
stored in the camera database and writes it to the repository
infrastructure directory so the local MediaMTX binary can consume it.

Keep the implementation intentionally small and readable.
"""
from pathlib import Path
import logging

from services.camera_db import camera_db

logger = logging.getLogger(__name__)


INFRA_PATH = Path(__file__).parent.parent.parent / "infrastructure" / "mediamtx.yml"


def _path_from_rtsp(rtsp_url: str, fallback: str) -> str:
    """Return the last path component of an RTSP URL or fallback to stream id.
    Examples:
      rtsp://localhost:8554/cam1 -> cam1
    """
    if not rtsp_url or "/" not in rtsp_url:
        return fallback
    try:
        return rtsp_url.rsplit("/", 1)[-1]
    except Exception:
        return fallback


def build_config(cameras: list[dict], rtsp_address: str = ":8554", log_level: str = "info") -> str:
    """Render a minimal mediamtx.yml as text from camera list.

    Only enabled cameras are included by convention.
    """
    header = (
        f"# Auto-generated by backend\n"
        f"# Do not edit manually if you rely on the backend deploy endpoint.\n"
        f"logLevel: {log_level}\n\n"
        f"rtspAddress: {rtsp_address}\n"
        f"rtspEncryption: \"no\"\n"
        f"rtspServerKey: \"\"\n"
        f"rtspServerCert: \"\"\n\n"
        f"paths:\n"
    )

    body_lines: list[str] = []
    for cam in cameras:
        if not cam.get("enabled", True):
            continue
        path = _path_from_rtsp(cam.get("rtsp_url", ""), cam.get("stream_id"))
        # minimal path entry
        body_lines.append(f"  {path}:")
        body_lines.append(f"    source: publisher")
        body_lines.append(f"    sourceOnDemand: no")
        body_lines.append("")

    if not body_lines:
        # keep a harmless placeholder so mediamtx has a valid file
        body_lines = ["  # No enabled cameras available"]

    return header + "\n".join(body_lines) + "\n"


def deploy_config(write: bool = True, enabled_only: bool = True) -> dict:
    """Generate and optionally write the mediamtx.yml file.

    Returns a simple status dict: {"path": str, "written": bool, "count": int}
    """
    cameras = camera_db.list_cameras(enabled_only=enabled_only)
    content = build_config(cameras)

    if write:
        INFRA_PATH.parent.mkdir(parents=True, exist_ok=True)
        INFRA_PATH.write_text(content, encoding="utf-8")
        logger.info("Wrote mediamtx config: %s", INFRA_PATH)
        return {"path": str(INFRA_PATH), "written": True, "count": len(cameras)}

    return {"path": str(INFRA_PATH), "written": False, "count": len(cameras), "preview": content}
